<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Timbers</title>
	<style>
	html,body,body div,span,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,abbr,address,cite,code,del,dfn,em,img,ins,kbd,q,samp,small,strong,sub,sup,var,b,i,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,figure,footer,header,hgroup,menu,nav,section,time,mark,audio,video{border:0;outline:0;font-size:100%;vertical-align:baseline;background:transparent;margin:0;padding:0}article,aside,figure,footer,header,hgroup,nav,section{display:block}object,embed{max-width:100%}html{overflow-y:scroll}ul{list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:none}a{font-size:100%;vertical-align:baseline;background:transparent;color:#00853F;text-decoration:none;margin:0;padding:0}del{text-decoration:line-through}abbr[title],dfn[title]{border-bottom:1px dotted #000;cursor:help}table{border-collapse:collapse;border-spacing:0;font-size:inherit}th{font-weight:bold;vertical-align:bottom}td{font-weight:normal;vertical-align:top}hr{display:block;height:1px;border:0;border-top:1px solid #ccc;margin:1em 0;padding:0}input,select{vertical-align:middle}pre{white-space:pre-line;word-wrap:break-word}input[type=checkbox]{vertical-align:baseline}select,input,textarea{font:99% sans-serif}small{font-size:85%}strong,th{font-weight:bold}td,td img{vertical-align:top}html body sub,html body sup{font-size:70%;line-height:0;position:relative;vertical-align:baseline}sup{top:-.4em}sub{bottom:-.2em}pre,code,kbd,samp{font-family:monospace, sans-serif}.clickable,label,input[type=button],input[type=submit],button{cursor:pointer}button,input,select,textarea{margin:0}button{width:auto;overflow:visible;border:0 none}.vertCent{display:table;height:100%}.vertCent > *{height:100%;display:table-cell;vertical-align:middle}.ie7 img{-ms-interpolation-mode:bicubic}.ie6{filter:expression(document.execCommand("BackgroundImageCache",false,true))}.clearfix:before,.clearfix:after{content:"\0020";display:block;height:0;overflow:hidden}.clearfix:after{clear:both}.clearfix{zoom:1}.ir{text-indent:-9999px}.abir{position:absolute;top:0;left:0}.ir *,.abir *{display:none}.nobr{white-space:nowrap}body{font-size:14px;font-family:Arial, Helvetica, Helmet, Freesans, sans-serif}body,select,input,textarea{color:#000}a:hover{color:#00853F;text-decoration:underline}a:link{-webkit-tap-highlight-color:rgba(140,198,63,0.1)}ins{background-color:#00853F;color:#000;text-decoration:none}mark{background-color:#00853F;color:#000;font-style:italic;font-weight:bold}input[type=radio],.ie6 input{vertical-align:text-bottom}*,a,a:focus,a:hover,a:active,a:active,a:focus{outline:0 none}.nolist,.nolist li{display:block;list-style:none;margin:0;padding:0}::-moz-selection,::selection{background:#8CC63F;color:#FFF;text-shadow:none}

	h1, h2 { text-align: center; margin: 0 0 1em 0; text-decoration: underline; font-size: 110% }
	p { margin: 0 0 1em 0 }
	#content { width: 980px; margin: 0 auto; }
	.copy { padding:  10px; }
	</style>
</head>
<body>
	<div id="content">
		<div class="mainimage">
			<img src="./main.jpg" alt="">
		</div>
		<div class="copy">
			<h1>CENTURYLINK HIGH SPEED DRIVE TO THE PLAYOFFS <br>
  				PORTLAND TIMBERS  TICKETS / SOCIAL MEDIA GIVEAWAY RULES</h1>
			<h2 align="left">NO PURCHASE NECESSARY.&nbsp; VOID  WHERE PROHIBITED.&nbsp; A PURCHASE WILL NOT  INCREASE YOUR CHANCES OF WINNING.</h2>
			<p><strong><u>Sponsor</u></strong>.&nbsp; CenturyLink / Portland Timbers</p>
			<p><strong><u>Entry Conditions</u></strong>.&nbsp; The CenturyLink  &ldquo;High Speed Drive to the Playoffs&rdquo; Timbers Tickets Social Media Giveaway (&ldquo;Giveaway&rdquo;)  is open to legal residents of Oregon who reside within a 75 mile radius of the Jeld-Wen Field  in Portland, OR.&nbsp; The Entrant must be at least 18 years of age  to enter.&nbsp; Only one entry per person;  first entry accepted and second or multiple Twitter entries after will not be considered  in @replies.&nbsp; Employees, officers,  directors and immediate family members of CenturyLink, Portland Timbers, its  affiliates, and any other entities involved in this Giveaway are not eligible  to enter or win.&nbsp; This Giveaway is void  where prohibited or restricted. </p>
			<p><strong><u>Entry Method</u></strong>.&nbsp; Portland  Timbers will post on their Facebook page and send Twitter messages with information  regarding the Giveaway.&nbsp; The Portland Timbers  will announce that the Giveaway is open via the @CenturyLinkPDX Twitter feed.&nbsp;  All @replies will naturally chronologically aggregate on the  @CenturyLinkPDX @reply page.&nbsp; </p>
			<p>All completed  entries become the property of Sponsors and will not be returned.&nbsp; Entries without all of the required blanks  completed will be disqualified and not entered into the Giveaway.&nbsp; All late, lost, or incomplete entries are not  considered valid entries.&nbsp; Any form of  entry other than as specified in these rules is prohibited.&nbsp; Sponsor will be collecting personal data  about Entrants when they register and enter the Giveaway.&nbsp; Please review Sponsors&rsquo; privacy policies at <a target="_blank" href="http://www.centurylink.com">www.centurylink.com</a> and <a target="_blank" href="http://www.portlandtimbers.com">www.PortlandTimbers.com</a>. By participating in the Giveaway, Entrants  agree to all of the terms and conditions of the Privacy and Social Media policies  of the Sponsors.&nbsp; By entering Entrants agree  to be bound by these official rules and the decisions of the Sponsors are final  and binding in all respects.&nbsp; </p>
			<p><strong><em>Twitter and FaceBook are not  sponsors of the Giveaway nor are they affiliated/responsible/liable in any way  to the Participants, Entrants or Winners of the Giveaway.&nbsp; All terms, conditions and policies of use for  Twitter and FaceBook Websites will apply to Participants, Entrants and Entries in  connection to the Giveaway.</em></strong></p>
			<p><strong><u>Promotion Period</u></strong>.&nbsp; The first  Giveaway begins on November 6, 2013 and ends when the 90th @replies  is recorded the @CenturyLinkPDX @reply  page.&nbsp; </p>
			<p><em>Additional Twitter opportunities may be  provided if the Portland Timbers remain in the playoffs.&nbsp; All additional Giveaway entry information  will be posted on the Portland Timbers Facebook page and via Timber Twitter messages.</em></p>
			<p><strong>Prize</strong>:&nbsp; Two tickets to the Portland  Timbers game held at Jeld-Wen Field in Portland, OR following the November 6th  Giveaway.&nbsp; Prize does not include any  travel, parking, hotel accommodations, meals, incidentals, etc. &nbsp;Prize valued at $100.00. </p>
			<p><strong><u>Prizes  Restrictions</u></strong>:&nbsp; Prize is not transferable.&nbsp; Sponsors will have the right to substitute  another prize package of equal or greater value, at its sole discretion.&nbsp; Sponsor may substitute for a cash prize or  goods or services with a value equal to or greater than the estimated retail  value of the original prize.&nbsp; All  expenses not specified are the sole responsibility of the Winner(s). No  transfer or cash redemption of prize is permitted except at the sole discretion  of the Sponsors, who may substitute a prize of equal or greater value if the  advertised prize becomes unavailable.&nbsp; Sponsors  are not responsible for lost or stolen prizes.&nbsp;  Refusal to agree and execute Sponsor&rsquo;s statement of eligibility and  release of liability will also result in disqualification and, at Sponsor&rsquo;s  sole discretion and time permitting, cause forfeiture of the Prize.&nbsp; Winner(s) will pick up Prize at game (Will  Call) and be required to sign the required documentation to accept the Prize.</p>
			<p><strong><u>Odds</u></strong>: Odds of winning a Prize depend on the number of eligible entries  received and being the 90th @replies on the @CenturyLinkPDX @reply  page during Promotion Period.</p>
			<p><strong><u>Grand Prize Selection</u></strong>:&nbsp; Only  one Prize will be awarded to one Winner for first playoff game.&nbsp; &nbsp;The  Winner will be determined by an authorized CenturyLink and Timbers employee.</p>
			<p><strong><u>Grand Prize Notification</u></strong><strong>:&nbsp; </strong>The potential Winner will be notified via  Twitter account immediately after Winner is determined.&nbsp; <strong>Winner must accept prize at the time of  notification or the prize will be forfeited and alternate Winner (the 91st  @replies entrant and so on if necessary) will be selected from among all  remaining eligible @replies entrants at the sponsor&rsquo;s discretion.&nbsp; In the event that the alternate Winner does  not respond or accept, another alternate Winner will be selected (see above).&nbsp; </strong></p>
			<p><strong><u>Taxation</u></strong><strong>:&nbsp; </strong>Winner(s) are solely responsible for any and  all federal, state, and local income taxes associated with his or her  Prize.&nbsp; Sponsors are not responsible for  and will not pay or in any way compensate Winners for taxes associated with  winning a Prize in this Giveaway. The Prize recipients and Grand Prize Winner  may be required to provide certain tax related documents to CenturyLink before  receiving a prize. If required by law, CenturyLink will issue Form 1099-MISC to  the Prize recipients and Grand Prize Winner reporting the taxable retail value  of his or her Prize. The Prize recipients and Grand Prize Winner should consult  his or her tax advisor about the tax implications of winning a Prize.</p>
			<p><strong><u>Waiver of Liability/Publicity Release</u></strong><strong>:&nbsp; </strong>By acceptance of Prize, Winner grants to  Sponsor the right to publicize such Winner&rsquo;s name, city and state/province of  residence and/or likeness in any medium now or hereafter devised worldwide  without limitation and without additional compensation or consideration,  notification or permission, unless prohibited by law.</p>
			<p><strong><u>General  Conditions</u></strong>: By entering,  participants agree (a) to these Official Rules and the decisions of the Sponsors  and the judging agency, which shall be final in all matters relating to the  Giveaway; (b) to release and hold harmless Sponsors and all affiliated  companies and directors, officers and employees from any and all claims,  liability or damages arising out of their participation and the acceptance and  use of a prize; (c) to permit Sponsors and its agents to use Winner&rsquo;s name,  city and/or likeness for advertising, promotional and publicity purposes in all  media without additional compensation and any prior review or approval; (d)  that under no circumstances will participant be permitted to obtain awards for,  and participant hereby waives all rights to claim punitive, incidental,  consequential or any other damages, other than for actual out-of-pocket  expenses; and (e) that all causes of action arising out of or connected with  this Giveaway, or any prizes awarded, shall be resolved individually, without  resort to any form class action.</p>
			<p>Sponsors are not responsible for printing or  typographical errors in any Giveaway-related materials; for stolen, lost, late,  misdirected, damaged, incomplete, illegible, or for transactions, entries or  communications that are processed late or incorrectly or lost due to computer  or electronic malfunction or human error.</p>
			<p>In the event of a dispute regarding any  entry, the entry will be deemed made by the authorized account holder of the First  and Last name submitted at the time of entry.&nbsp;  Sponsors reserve the right in their sole discretion, to cancel,  terminate, modify or suspend the Giveaway and award Giveaway prizes from among  all eligible entries received prior to cancellation or termination. Sponsors  also reserve the right to disqualify any individual who does not comply with  these Official Rules.</p>
			<p><strong>CAUTION:</strong>&nbsp; ANY  ATTEMPT BY AN ENTRANT TO DELIBERATELY DAMAGE ANY WEB SITE OR UNDERMINE THE  LEGITIMATE OPERATION OF THIS PROMOTION IS A VIOLATION OF CRIMINAL AND CIVIL  LAW. SHOULD SUCH AN ATTEMPT BE MADE, SPONSOR RESERVES THE RIGHT TO SEEK DAMAGES  FROM ANY SUCH INDIVIDUAL TO THE FULLEST EXTENT PERMITTED BY LAW. </p>
			<p><strong><u>Governing Law</u></strong>.&nbsp; Giveaway  will be governed by and construed in accordance with the laws of the State of Louisiana.&nbsp; All federal, state and local laws and  regulations apply.</p>
			<p><strong><u>Winners List</u></strong>.&nbsp; All  inquiries concerning the Giveaway or the list of Winner(s) may be directed to  by and no later than 01/31/14:</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; CenturyLink, Attn: Christina Hixson, 931  14th Street, 8th Floor, Denver, CO 80202.</p>
			<p>&nbsp;</p>

		</div>
	</div>
</body>
</html>